---
functional:
  - Пользователь должен иметь возможность соревноваться с ботом или с другим пользователем в решении задач
  - Пользователь должен иметь возможность видеть написание кода соперника
  - Пользователь должен иметь возможность видеть результаты запуска тестов
  - Пользователь должен иметь возможность видеть свой рейтинг за неделю, месяц и за все время
  - Пользователь должен иметь возможность общаться с соперником и зрителями в чате
  - Пользователь должен иметь возможность общаться в чате только будучи зарегестрированным пользователем
  - Пользователь должен иметь возможность создавать игру самостоятельно
  - Пользователь должен иметь возможность вступать в открытые игры
  - Пользователь должен иметь возможность в запущенную игру зайти в качестве зрителя
  - Пользователь должен иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность выбирать игру по уровню сложности
  - Пользователь должен иметь возможность менять язык задач — русский или английский
  - Пользователь должен иметь возможность просматривать завершенную игру в записи
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сат должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Пользователь не должен иметь возможность редактировать код соперника
  - Пользователь не должен иметь возможность редактировать код в завершенной игре
  - Пользователь должен иметь возможность просматривать рейтинг других пользователей
  - Пользователь должен иметь возможность участвовать в турнирах
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность менять настройки своего профиля
  - Пользователь должен иметь возможность просматривать содержимое заданий
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность выйти из аккаунта
