---
functional:
  - Пользователь должен иметь возможность создавать игру самостоятельно
  - Пользователь должен иметь возможность вступать в открытые игры 
  - Пользователь должен иметь возможность видеть написание кода соперника
  - Пользователь должен иметь возможность сдаться сопернику в игре
  - Пользователь должен иметь возможность сбросить редактор кода в игре
  - Пользователь должен иметь возможность видеть результаты запуска тестов 
  - Пользователь должен иметь возможность менять язык программирования во время решения задания
  - Пользователь должен иметь возможность менять язык описания задания — русский или английский
  - Пользователь должен иметь возможность видеть свой рейтинг
  - Пользователь должен иметь возможность просматривать рейтинг других пользователей
  - Пользователь должен иметь возможность общаться с соперником и зрителями в чате
  - Пользователь должен иметь возможность просматривать завершенные игры в записи
  - Пользователь должен иметь возможность присоединиться к игре в качестве зрителя
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сат должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Пользователь не должен иметь возможность редактировать код соперника
  - Пользователь не должен иметь возможность менять язык програмирования соперника
  - Пользователь не должен иметь возможность редактировать код в завершенной игре
  - Пользователь не должен иметь возможность начать игру, если предыдущая не завершена
  - Пользователь не должен иметь возможность редактировать текст задания в игре
  - Зрители игры не могут писать код и вносить изменения в код участников
